"""Public API for the RPS: Animal Showdown domain engine."""

from .errors import EngineError, EngineValidationError, InvalidTransitionError
from .match import play_round, resolve_round, start_match, validate_match_state
from .models import (
    ALL_STRATEGY_CONDITIONS,
    BracketMatch,
    BracketMatchStatus,
    BracketRoundState,
    Competitor,
    MatchRound,
    MatchState,
    MatchStatus,
    MatchTransition,
    Move,
    ProbabilityDistribution,
    RoundOutcome,
    Strategy,
    StrategyCondition,
    TournamentState,
    TournamentStatus,
    TournamentTransition,
    TrainingRound,
    TrainingState,
    TrainingTransition,
    TrainingWinner,
)
from .randomness import RandomSource, SystemRandomSource
from .strategy import condition_for_player, sample_move
from .snapshots import (
    SNAPSHOT_SCHEMA_VERSION,
    TOURNAMENT_SNAPSHOT_KIND,
    canonical_uuid,
    strategy_from_payload,
    strategy_to_payload,
    tournament_state_from_snapshot,
    tournament_state_to_snapshot,
)
from .tournament import (
    play_active_match_round,
    start_tournament,
    validate_tournament_state,
)
from .training import play_training_round, start_training

__all__ = [
    "ALL_STRATEGY_CONDITIONS",
    "BracketMatch",
    "BracketMatchStatus",
    "BracketRoundState",
    "Competitor",
    "EngineError",
    "EngineValidationError",
    "InvalidTransitionError",
    "MatchRound",
    "MatchState",
    "MatchStatus",
    "MatchTransition",
    "Move",
    "ProbabilityDistribution",
    "RandomSource",
    "RoundOutcome",
    "SNAPSHOT_SCHEMA_VERSION",
    "Strategy",
    "StrategyCondition",
    "SystemRandomSource",
    "TOURNAMENT_SNAPSHOT_KIND",
    "TournamentState",
    "TournamentStatus",
    "TournamentTransition",
    "TrainingRound",
    "TrainingState",
    "TrainingTransition",
    "TrainingWinner",
    "condition_for_player",
    "canonical_uuid",
    "play_active_match_round",
    "play_round",
    "play_training_round",
    "resolve_round",
    "sample_move",
    "start_match",
    "start_tournament",
    "start_training",
    "strategy_from_payload",
    "strategy_to_payload",
    "tournament_state_from_snapshot",
    "tournament_state_to_snapshot",
    "validate_match_state",
    "validate_tournament_state",
]
