export const locales = ["pt-BR", "en", "zh-CN", "ar"] as const;
export type Locale = (typeof locales)[number];

export const localeLabels: Record<Locale, string> = {
  "pt-BR": "🇧🇷 Português",
  en: "🇺🇸 English",
  "zh-CN": "🇨🇳 简体中文",
  ar: "🌐 العربية الفصحى",
};

// Keep the accessible language name separate from its visual flag treatment.
// Some Windows controls render regional-indicator emoji as "BR", "US" or "CN".
export const localeNames: Record<Locale, string> = {
  "pt-BR": "Português",
  en: "English",
  "zh-CN": "简体中文",
  ar: "العربية الفصحى",
};

// This visual roster is intentionally language-neutral and is shared by every locale.
// Thirteen items per row keep the full roster legible on the arena landing page.
export const animalShowcaseRows = [
  ["🦅", "🐼", "🦘", "🦦", "🐵", "🐓", "🐂", "🐯", "🐘", "🐻", "🐙", "🦍", "🐎"],
  ["🦙", "🦌", "🐪", "🐐", "🦎", "🐱", "🦓", "🦜", "🐦", "🦁", "🐧", "🐟", "🦈"],
] as const;

export const animalNames: Record<Locale, Record<string, string>> = {
  "pt-BR": { eagle:"Águia", panda:"Panda", kangaroo:"Canguru", otter:"Lontra", monkey:"Macaco japonês", rooster:"Galo", bull:"Touro", tiger:"Tigre", elephant:"Elefante", bear:"Urso", octopus:"Polvo do Ártico", llama:"Lhama", white_tailed_deer:"Veado-de-cauda-branca", camel:"Camelo", goat:"Cabra", lizard:"Dragão de Komodo", angora_cat:"Gato angorá", zebra:"Zebra", macaw:"Arara", crane:"Grou-coroado", lion:"Leão", penguin:"Pinguim", gorilla:"Gorila", hilsa:"Hilsa", horse:"Cavalo", shark:"Tubarão" },
  en: { eagle:"Eagle", panda:"Panda", kangaroo:"Kangaroo", otter:"Otter", monkey:"Japanese macaque", rooster:"Rooster", bull:"Bull", tiger:"Tiger", elephant:"Elephant", bear:"Bear", octopus:"Arctic octopus", llama:"Llama", white_tailed_deer:"White-tailed deer", camel:"Camel", goat:"Goat", lizard:"Komodo dragon", angora_cat:"Turkish Angora", zebra:"Zebra", macaw:"Macaw", crane:"Crowned crane", lion:"Lion", penguin:"Penguin", gorilla:"Gorilla", hilsa:"Hilsa", horse:"Horse", shark:"Shark" },
  "zh-CN": { eagle:"鹰", panda:"熊猫", kangaroo:"袋鼠", otter:"水獭", monkey:"日本猕猴", rooster:"公鸡", bull:"公牛", tiger:"老虎", elephant:"大象", bear:"熊", octopus:"北极章鱼", llama:"羊驼", white_tailed_deer:"白尾鹿", camel:"骆驼", goat:"山羊", lizard:"科莫多巨蜥", angora_cat:"土耳其安哥拉猫", zebra:"斑马", macaw:"金刚鹦鹉", crane:"冠鹤", lion:"狮子", penguin:"企鹅", gorilla:"大猩猩", hilsa:"希尔萨鱼", horse:"马", shark:"鲨鱼" },
  ar: { eagle:"نسر", panda:"باندا", kangaroo:"كنغر", otter:"قضاعة", monkey:"مكاك ياباني", rooster:"ديك", bull:"ثور", tiger:"نمر", elephant:"فيل", bear:"دب", octopus:"أخطبوط القطب الشمالي", llama:"لاما", white_tailed_deer:"أيل أبيض الذيل", camel:"جمل", goat:"ماعز", lizard:"تنين كومودو", angora_cat:"قط أنغورا", zebra:"حمار وحشي", macaw:"ببغاء المكاو", crane:"كركي متوج", lion:"أسد", penguin:"بطريق", gorilla:"غوريلا", hilsa:"سمك هيلسا", horse:"حصان", shark:"قرش" },
};

// Latin scientific names are deliberately shared across locales.
export const scientificNames: Record<string, string> = {
  eagle: "Haliaeetus leucocephalus",
  panda: "Ailuropoda melanoleuca",
  kangaroo: "Macropus giganteus",
  otter: "Lontra canadensis",
  monkey: "Macaca fuscata",
  rooster: "Gallus gallus domesticus",
  bull: "Bos taurus",
  tiger: "Panthera tigris",
  elephant: "Elephas maximus",
  bear: "Ursus arctos",
  octopus: "Bathypolypus arcticus",
  llama: "Lama glama",
  white_tailed_deer: "Odocoileus virginianus",
  camel: "Camelus dromedarius",
  goat: "Capra falconeri",
  lizard: "Varanus komodoensis",
  angora_cat: "Felis catus",
  zebra: "Equus quagga",
  macaw: "Ara ararauna",
  crane: "Balearica regulorum",
  lion: "Panthera leo",
  penguin: "Aptenodytes forsteri",
  gorilla: "Gorilla beringei beringei",
  hilsa: "Tenualosa ilisha",
  horse: "Equus ferus caballus",
  shark: "Sphyrna lewini",
};

export const interfaceText: Record<Locale, Record<string, string>> = {
  "pt-BR": { liveArena:"ARENA RPS AO VIVO", language:"Idioma", sponsorImage:"Espaço para imagem da marca patrocinadora", sponsorMessage:"Quero patrocinar o RPS", listenAnimalSound:"Ouvir som do animal", random:"Aleatorizar", randomAll:"Aleatorizar todas", strategyIntro:"Você define como seu personagem escolhe Pedra, Papel ou Tesoura após cada resultado.", trainingYou:"Você", trainingCharacter:"Seu personagem", trainingRound:"Rodada", trainingResult:"Resultado do treino", bestOf1:"Melhor de 1", bestOf3:"Melhor de 3", bestOf5:"Melhor de 5", bestOf7:"Melhor de 7", speed05:"0,5×", speed1:"1×", speed2:"2×", speed4:"4×", speed8:"8×", countdownSequence:"Contagem: 3 · 2 · 1", rock:"Pedra", paper:"Papel", scissors:"Tesoura", player:"Jogador", challenger:"Desafiante", versus:"VS", readySuffix:"está pronto", worldMap:"Mapa-múndi dos animais", mapHint:"Deslize pelo mapa para explorar os países.", mapEnlarge:"Ampliar mapa", mapReduce:"Reduzir mapa", northAmerica:"América do Norte", southAmerica:"América do Sul", europe:"Europa", africa:"África", asia:"Ásia", oceania:"Oceania", antarctica:"Antártida", atlanticOcean:"Oceano Atlântico", arcticOcean:"Oceano Ártico", officialRound:"Rodada oficial", bye:"BYE", champion:"Campeão", realtime:"Tempo real", connecting:"Conectando", snapshot:"Sincronizado", live:"Ao vivo", fallback:"Reconexão pendente", winner:"Vencedor", status_active:"Em disputa", status_pending:"Aguardando", status_completed:"Encerrada", event_tournament_started:"Torneio iniciado", event_match_started:"Partida iniciada", event_round_resolved:"Rodada resolvida", event_heart_lost:"Coração perdido", event_player_eliminated:"Jogador eliminado", event_match_completed:"Partida encerrada", event_player_advanced:"Jogador avançou", event_bye:"Avanço por BYE", event_champion:"Campeão definido", createRateLimited:"Limite temporário de criação de torneios. Tente novamente mais tarde." },
  en: { liveArena:"LIVE RPS ARENA", language:"Language", sponsorImage:"Sponsor brand image area", sponsorMessage:"I want to sponsor RPS", listenAnimalSound:"Play animal sound", random:"Randomize", randomAll:"Randomize all", strategyIntro:"Set how your character chooses Rock, Paper or Scissors after each result.", trainingYou:"You", trainingCharacter:"Your character", trainingRound:"Round", trainingResult:"Training result", bestOf1:"Best of 1", bestOf3:"Best of 3", bestOf5:"Best of 5", bestOf7:"Best of 7", speed05:"0.5×", speed1:"1×", speed2:"2×", speed4:"4×", speed8:"8×", countdownSequence:"Countdown: 3 · 2 · 1", rock:"Rock", paper:"Paper", scissors:"Scissors", player:"Player", challenger:"Challenger", versus:"VS", readySuffix:"is ready", worldMap:"Animal world map", mapHint:"Scroll the map to explore countries.", mapEnlarge:"Enlarge map", mapReduce:"Reduce map", northAmerica:"North America", southAmerica:"South America", europe:"Europe", africa:"Africa", asia:"Asia", oceania:"Oceania", antarctica:"Antarctica", atlanticOcean:"Atlantic Ocean", arcticOcean:"Arctic Ocean", officialRound:"Official round", bye:"BYE", champion:"Champion", realtime:"Realtime", connecting:"Connecting", snapshot:"Synchronized", live:"Live", fallback:"Reconnect pending", winner:"Winner", status_active:"Active", status_pending:"Waiting", status_completed:"Completed", event_tournament_started:"Tournament started", event_match_started:"Match started", event_round_resolved:"Round resolved", event_heart_lost:"Heart lost", event_player_eliminated:"Player eliminated", event_match_completed:"Match completed", event_player_advanced:"Player advanced", event_bye:"Advanced by BYE", event_champion:"Champion decided", createRateLimited:"Temporary tournament creation limit reached. Please try again later." },
  "zh-CN": { liveArena:"RPS 直播竞技场", language:"语言", sponsorImage:"赞助商品牌图片区域", sponsorMessage:"我想赞助 RPS", listenAnimalSound:"播放动物叫声", random:"随机", randomAll:"全部随机", strategyIntro:"设定你的角色在每种结果后如何选择石头、布或剪刀。", trainingYou:"你", trainingCharacter:"你的角色", trainingRound:"回合", trainingResult:"训练结果", bestOf1:"一局定胜负", bestOf3:"三局两胜", bestOf5:"五局三胜", bestOf7:"七局四胜", speed05:"0.5×", speed1:"1×", speed2:"2×", speed4:"4×", speed8:"8×", countdownSequence:"倒计时：3 · 2 · 1", rock:"石头", paper:"布", scissors:"剪刀", player:"玩家", challenger:"挑战者", versus:"对阵", readySuffix:"已准备就绪", worldMap:"动物世界地图", mapHint:"滑动地图查看各个国家。", mapEnlarge:"放大地图", mapReduce:"缩小地图", northAmerica:"北美洲", southAmerica:"南美洲", europe:"欧洲", africa:"非洲", asia:"亚洲", oceania:"大洋洲", antarctica:"南极洲", atlanticOcean:"大西洋", arcticOcean:"北冰洋", officialRound:"官方回合", bye:"轮空", champion:"冠军", realtime:"实时", connecting:"正在连接", snapshot:"已同步", live:"实时在线", fallback:"等待重连", winner:"胜者", status_active:"进行中", status_pending:"等待中", status_completed:"已结束", event_tournament_started:"比赛开始", event_match_started:"Partida iniciada", event_round_resolved:"回合结束", event_heart_lost:"失去一颗心", event_player_eliminated:"选手淘汰", event_match_completed:"对局结束", event_player_advanced:"选手晋级", event_bye:"轮空晋级", event_champion:"冠军产生", createRateLimited:"已达到临时创建上限，请稍后再试。" },
  ar: { liveArena:"ساحة RPS المباشرة", language:"اللغة", sponsorImage:"مساحة لصورة العلامة التجارية للراعي", sponsorMessage:"أريد رعاية RPS", listenAnimalSound:"تشغيل صوت الحيوان", random:"عشوائي", randomAll:"عشوائي للكل", strategyIntro:"حدّد كيف يختار شخصك حجرًا أو ورقًا أو مقصًا بعد كل نتيجة.", trainingYou:"أنت", trainingCharacter:"شخصك", trainingRound:"الجولة", trainingResult:"نتيجة التدريب", bestOf1:"الأفضل من جولة واحدة", bestOf3:"الأفضل من ثلاث جولات", bestOf5:"الأفضل من خمس جولات", bestOf7:"الأفضل من سبع جولات", speed05:"٠٫٥×", speed1:"١×", speed2:"٢×", speed4:"٤×", speed8:"٨×", countdownSequence:"العد التنازلي: ٣ · ٢ · ١", rock:"حجر", paper:"ورق", scissors:"مقص", player:"لاعب", challenger:"المتحدي", versus:"ضد", readySuffix:"جاهز", worldMap:"خريطة عالم الحيوانات", mapHint:"مرر الخريطة لاستكشاف البلدان.", mapEnlarge:"تكبير الخريطة", mapReduce:"تصغير الخريطة", northAmerica:"أمريكا الشمالية", southAmerica:"أمريكا الجنوبية", europe:"أوروبا", africa:"أفريقيا", asia:"آسيا", oceania:"أوقيانوسيا", antarctica:"القارة القطبية الجنوبية", atlanticOcean:"المحيط الأطلسي", arcticOcean:"المحيط المتجمد الشمالي", officialRound:"الجولة الرسمية", bye:"تأهل تلقائي", champion:"البطل", realtime:"الوقت الفعلي", connecting:"جارٍ الاتصال", snapshot:"تمت المزامنة", live:"مباشر", fallback:"بانتظار إعادة الاتصال", winner:"الفائز", status_active:"جارية", status_pending:"قيد الانتظار", status_completed:"مكتملة", event_tournament_started:"بدأت البطولة", event_match_started:"بدأت المواجهة", event_round_resolved:"حُسمت الجولة", event_heart_lost:"خسارة قلب", event_player_eliminated:"إقصاء لاعب", event_match_completed:"انتهت المواجهة", event_player_advanced:"تأهل لاعب", event_bye:"تأهل تلقائي", event_champion:"تحديد البطل", createRateLimited:"تم بلوغ الحد المؤقت لإنشاء البطولات. حاول مرة أخرى لاحقًا." },
};

// Practice-only avatar names are kept with the rest of the interface copy.
// They never identify, replace, or persist a tournament animal.
Object.assign(interfaceText["pt-BR"], { waitingTitle:"Você está pronto para o torneio", waitingOrganizer:"Aguardando o organizador iniciar o torneio…", waitingRegistered:"Inscrição confirmada", waitingStrategy:"Estratégia salva e pronta", waitingNotStarted:"O torneio ainda não começou", waitingNoRefresh:"Não é necessário atualizar a página", waitingAutoStart:"O sistema levará você automaticamente quando o torneio começar.", enterTraining:"ENTRAR NO TREINO", guestTraining:"Treinar", chooseTrainingAnimal:"Escolha o animal do treino", chooseAvatar:"Escolha seu avatar visual", chooseAvatarHint:"Ele representa você apenas neste treino e não altera seu animal do torneio.", trainingMode:"MODO TREINO", tournamentAnimal:"Animal do torneio", trainingAnimal:"Animal do treino", trainingComplete:"Treino concluído", trainingChampion:"Campeão do treino", returnWaiting:"VOLTAR À SALA DE ESPERA", returnAnimalSelection:"VOLTAR À ESCOLHA DO ANIMAL", avatarExplorer:"Explorador", avatarStudent:"Estudante", avatarArtist:"Artista", avatarScientist:"Cientista", avatarChef:"Cozinheiro", avatarAthlete:"Atleta" });
Object.assign(interfaceText.en, { waitingTitle:"You are ready for the tournament", waitingOrganizer:"Waiting for the organizer to start the tournament…", waitingRegistered:"Registration confirmed", waitingStrategy:"Strategy saved and ready", waitingNotStarted:"The tournament has not started yet", waitingNoRefresh:"No page refresh is needed", waitingAutoStart:"The system will take you there automatically when the tournament starts.", enterTraining:"ENTER TRAINING", guestTraining:"Train", chooseTrainingAnimal:"Choose a training animal", chooseAvatar:"Choose your visual avatar", chooseAvatarHint:"It represents you only in this training and does not change your tournament animal.", trainingMode:"TRAINING MODE", tournamentAnimal:"Tournament animal", trainingAnimal:"Training animal", trainingComplete:"Training complete", trainingChampion:"Training champion", returnWaiting:"RETURN TO WAITING ROOM", returnAnimalSelection:"RETURN TO ANIMAL SELECTION", avatarExplorer:"Explorer", avatarStudent:"Student", avatarArtist:"Artist", avatarScientist:"Scientist", avatarChef:"Chef", avatarAthlete:"Athlete" });
Object.assign(interfaceText["zh-CN"], { waitingTitle:"你已准备好参加锦标赛", waitingOrganizer:"正在等待组织者开始锦标赛…", waitingRegistered:"报名已确认", waitingStrategy:"策略已保存并准备就绪", waitingNotStarted:"锦标赛尚未开始", waitingNoRefresh:"无需刷新页面", waitingAutoStart:"锦标赛开始后，系统会自动带你进入竞技场。", enterTraining:"进入训练", guestTraining:"训练", chooseTrainingAnimal:"选择训练动物", chooseAvatar:"选择你的视觉头像", chooseAvatarHint:"它只代表你本次训练，不会更改你的锦标赛动物。", trainingMode:"训练模式", tournamentAnimal:"锦标赛动物", trainingAnimal:"训练动物", trainingComplete:"训练完成", trainingChampion:"训练冠军", returnWaiting:"返回等候室", returnAnimalSelection:"返回动物选择", avatarExplorer:"探险家", avatarStudent:"学生", avatarArtist:"艺术家", avatarScientist:"科学家", avatarChef:"厨师", avatarAthlete:"运动员" });
Object.assign(interfaceText.ar, { waitingTitle:"أنت مستعد للبطولة", waitingOrganizer:"بانتظار المنظم لبدء البطولة…", waitingRegistered:"تم تأكيد التسجيل", waitingStrategy:"حُفظت الاستراتيجية وهي جاهزة", waitingNotStarted:"لم تبدأ البطولة بعد", waitingNoRefresh:"لا حاجة لتحديث الصفحة", waitingAutoStart:"سينقلك النظام تلقائيًا عند بدء البطولة.", enterTraining:"ادخل التدريب", guestTraining:"تدرّب", chooseTrainingAnimal:"اختر حيوان التدريب", chooseAvatar:"اختر صورتك الرمزية", chooseAvatarHint:"تمثلك في هذا التدريب فقط ولا تغيّر حيوان البطولة.", trainingMode:"وضع التدريب", tournamentAnimal:"حيوان البطولة", trainingAnimal:"حيوان التدريب", trainingComplete:"اكتمل التدريب", trainingChampion:"بطل التدريب", returnWaiting:"العودة إلى غرفة الانتظار", returnAnimalSelection:"العودة إلى اختيار الحيوان", avatarExplorer:"مستكشف", avatarStudent:"طالب", avatarArtist:"فنان", avatarScientist:"عالِم", avatarChef:"طاهٍ", avatarAthlete:"رياضي" });

Object.assign(interfaceText["pt-BR"], { chooseTrainer:"Escolha o treinador", trainerMan:"Homem", trainerWoman:"Mulher", trainerGirl:"Menina", trainerBoy:"Menino", trainerBaby:"Bebê", trainerOlderMan:"Idoso", trainerOlderWoman:"Idosa", trainerAlien:"Alienígena" });
Object.assign(interfaceText.en, { chooseTrainer:"Choose the trainer", trainerMan:"Man", trainerWoman:"Woman", trainerGirl:"Girl", trainerBoy:"Boy", trainerBaby:"Baby", trainerOlderMan:"Older man", trainerOlderWoman:"Older woman", trainerAlien:"Alien" });
Object.assign(interfaceText["zh-CN"], { chooseTrainer:"选择训练师", trainerMan:"男性", trainerWoman:"女性", trainerGirl:"女孩", trainerBoy:"男孩", trainerBaby:"婴儿", trainerOlderMan:"老年男性", trainerOlderWoman:"老年女性", trainerAlien:"外星人" });
Object.assign(interfaceText.ar, { chooseTrainer:"اختر المدرب", trainerMan:"رجل", trainerWoman:"امرأة", trainerGirl:"طفلة", trainerBoy:"طفل", trainerBaby:"رضيع", trainerOlderMan:"رجل مسن", trainerOlderWoman:"امرأة مسنة", trainerAlien:"كائن فضائي" });

Object.assign(interfaceText["pt-BR"], { chooseHearts:"Escolha a quantidade de corações", heartsCount:"Corações" });
Object.assign(interfaceText.en, { chooseHearts:"Choose the number of hearts", heartsCount:"Hearts" });
Object.assign(interfaceText["zh-CN"], { chooseHearts:"选择爱心数量", heartsCount:"爱心" });
Object.assign(interfaceText.ar, { chooseHearts:"اختر عدد القلوب", heartsCount:"القلوب" });

Object.assign(interfaceText["pt-BR"], { startTraining:"INICIAR TREINO" });
Object.assign(interfaceText.en, { startTraining:"START TRAINING" });
Object.assign(interfaceText["zh-CN"], { startTraining:"开始训练" });
Object.assign(interfaceText.ar, { startTraining:"ابدأ التدريب" });

Object.assign(interfaceText["pt-BR"], { waitingReady:"Participante está READY", waitingAutoStart:"O sistema levará você automaticamente quando o torneio começar.", playAnimalRush:"JOGAR ANIMAL RUSH", animalRushTitle:"ANIMAL RUSH", animalRushInstruction:"Escolha o símbolo que vence o que aparecer na tela.", animalRushStats:"Pontuação do Animal Rush", rushScore:"Pontuação", rushStreak:"Sequência", rushBestStreak:"Melhor sequência", rushTime:"Tempo para responder", rushCorrect:"Correto!", rushIncorrect:"Resposta incorreta.", rushTimeout:"O tempo acabou.", rushCorrectAnswer:"A resposta correta era", rushSequenceEnded:"Sequência encerrada!", rushPlayAgain:"JOGAR NOVAMENTE", tournamentStartedNotice:"O torneio começou!" });
Object.assign(interfaceText.en, { waitingReady:"Participant is READY", waitingAutoStart:"The system will take you there automatically when the tournament starts.", playAnimalRush:"PLAY ANIMAL RUSH", animalRushTitle:"ANIMAL RUSH", animalRushInstruction:"Choose the symbol that defeats the one shown on screen.", animalRushStats:"Animal Rush score", rushScore:"Score", rushStreak:"Streak", rushBestStreak:"Best streak", rushTime:"Time to answer", rushCorrect:"Correct!", rushIncorrect:"Incorrect answer.", rushTimeout:"Time is up.", rushCorrectAnswer:"The correct answer was", rushSequenceEnded:"Streak ended!", rushPlayAgain:"PLAY AGAIN", tournamentStartedNotice:"The tournament has started!" });
Object.assign(interfaceText["zh-CN"], { waitingReady:"参赛者已准备就绪", waitingAutoStart:"锦标赛开始后，系统会自动带你进入竞技场。", playAnimalRush:"玩 ANIMAL RUSH", animalRushTitle:"ANIMAL RUSH", animalRushInstruction:"选择能够击败屏幕上符号的选项。", animalRushStats:"Animal Rush 得分", rushScore:"得分", rushStreak:"连续答对", rushBestStreak:"最佳连续记录", rushTime:"答题时间", rushCorrect:"正确！", rushIncorrect:"回答错误。", rushTimeout:"时间到。", rushCorrectAnswer:"正确答案是", rushSequenceEnded:"连续记录结束！", rushPlayAgain:"再玩一次", tournamentStartedNotice:"锦标赛开始了！" });
Object.assign(interfaceText.ar, { waitingReady:"المشارك جاهز", waitingAutoStart:"سينقلك النظام تلقائيًا عند بدء البطولة.", playAnimalRush:"العب ANIMAL RUSH", animalRushTitle:"ANIMAL RUSH", animalRushInstruction:"اختر الرمز الذي يهزم الرمز الظاهر على الشاشة.", animalRushStats:"نتيجة Animal Rush", rushScore:"النقاط", rushStreak:"السلسلة الحالية", rushBestStreak:"أفضل سلسلة", rushTime:"وقت الإجابة", rushCorrect:"إجابة صحيحة!", rushIncorrect:"إجابة غير صحيحة.", rushTimeout:"انتهى الوقت.", rushCorrectAnswer:"كانت الإجابة الصحيحة", rushSequenceEnded:"انتهت السلسلة!", rushPlayAgain:"العب مرة أخرى", tournamentStartedNotice:"بدأت البطولة!" });

Object.assign(interfaceText["pt-BR"], { participantStatus_joined:"Entrou", participantStatus_choosing_character:"Escolhendo personagem", participantStatus_configuring_strategy:"Configurando estratégia", participantStatus_ready:"Pronto", participantStatus_disconnected:"Desconectado", participantStatus_removed:"Removido" });
Object.assign(interfaceText.en, { participantStatus_joined:"Joined", participantStatus_choosing_character:"Choosing character", participantStatus_configuring_strategy:"Configuring strategy", participantStatus_ready:"Ready", participantStatus_disconnected:"Disconnected", participantStatus_removed:"Removed" });
Object.assign(interfaceText["zh-CN"], { participantStatus_joined:"已加入", participantStatus_choosing_character:"正在选择角色", participantStatus_configuring_strategy:"正在配置策略", participantStatus_ready:"已准备", participantStatus_disconnected:"已断开连接", participantStatus_removed:"已移除" });
Object.assign(interfaceText.ar, { participantStatus_joined:"انضم", participantStatus_choosing_character:"يختار الشخصية", participantStatus_configuring_strategy:"يضبط الاستراتيجية", participantStatus_ready:"جاهز", participantStatus_disconnected:"غير متصل", participantStatus_removed:"تمت إزالته" });

Object.assign(interfaceText["pt-BR"], { secondChance:"Partida de Segunda Chance", secondChanceWaiting:"Sorteado para aguardar a Segunda Chance", cinema_waiting:"Participante aguardando a Segunda Chance", cinema_secondChance:"Segunda Chance: um eliminado retorna como Zumbi!", event_player_waiting:"Aguardando a Segunda Chance", event_second_chance_selected:"Selecionado para a Segunda Chance", event_second_chance_match_started:"Partida de Segunda Chance iniciada", event_second_chance_completed:"Segunda Chance concluída", event_player_eliminated_definitively:"Eliminado definitivamente" });
Object.assign(interfaceText.en, { secondChance:"Second Chance match", secondChanceWaiting:"Drawn to wait for Second Chance", cinema_waiting:"Participant waiting for Second Chance", cinema_secondChance:"Second Chance: an eliminated player returns as a Zombie!", event_player_waiting:"Waiting for Second Chance", event_second_chance_selected:"Selected for Second Chance", event_second_chance_match_started:"Second Chance match started", event_second_chance_completed:"Second Chance completed", event_player_eliminated_definitively:"Definitively eliminated" });
Object.assign(interfaceText["zh-CN"], { secondChance:"第二次机会对决", secondChanceWaiting:"抽中等待第二次机会对决", cinema_waiting:"参赛者等待第二次机会对决", cinema_secondChance:"第二次机会：被淘汰的选手以僵尸身份回归！", event_player_waiting:"等待第二次机会对决", event_second_chance_selected:"获选获得第二次机会", event_second_chance_match_started:"第二次机会对决开始", event_second_chance_completed:"第二次机会对决结束", event_player_eliminated_definitively:"最终淘汰" });
Object.assign(interfaceText.ar, { secondChance:"مباراة الفرصة الثانية", secondChanceWaiting:"اختير بالقرعة لانتظار الفرصة الثانية", cinema_waiting:"مشارك ينتظر الفرصة الثانية", cinema_secondChance:"الفرصة الثانية: يعود لاعب مُقصى بصفة زومبي!", event_player_waiting:"ينتظر الفرصة الثانية", event_second_chance_selected:"اختير للفرصة الثانية", event_second_chance_match_started:"بدأت مباراة الفرصة الثانية", event_second_chance_completed:"انتهت الفرصة الثانية", event_player_eliminated_definitively:"أُقصي نهائيًا" });

Object.assign(interfaceText["pt-BR"], { zombie:"Zumbi", secondChanceReturn:"Retorno pela Segunda Chance" });
Object.assign(interfaceText.en, { zombie:"Zombie", secondChanceReturn:"Return through Second Chance" });
Object.assign(interfaceText["zh-CN"], { zombie:"僵尸", secondChanceReturn:"通过第二次机会回归" });
Object.assign(interfaceText.ar, { zombie:"زومبي", secondChanceReturn:"العودة عبر الفرصة الثانية" });

export function animalName(locale: Locale, animal: string): string { return animalNames[locale][animal] ?? animal; }
export function scientificName(animal: string): string { return scientificNames[animal] ?? animal; }
export function uiText(locale: Locale, key: string): string { return interfaceText[locale][key] ?? key; }
const specialRegions: Record<Locale, Record<string, string>> = {
  "pt-BR": { arctic:"Ártico", southPole:"Polo Sul" },
  en: { arctic:"Arctic", southPole:"South Pole" },
  "zh-CN": { arctic:"北极地区", southPole:"南极" },
  ar: { arctic:"منطقة القطب الشمالي", southPole:"القطب الجنوبي" },
};
export function regionName(locale: Locale, region: string): string {
  return specialRegions[locale][region] ?? new Intl.DisplayNames([locale], { type: "region" }).of(region) ?? region;
}

const messages = {
  "pt-BR": { home:"Início", join:"Entrar no torneio", create:"Criar torneio", sponsor:"Quero patrocinar", sponsored:"Patrocinado por", tagline:"🦅 🐼 🦘 🦦 🐵 🐓 🐂 🐯 🐘 🐻 🐙 🦍 🐎 🦙 🦌 🐪 🐐 🦎 🐱 🦓 🦜 🐦 🦁 🐧 🐟 🦈", createTitle:"Monte a sua arena", joinTitle:"Entre na arena", capacity:"Capacidade máxima", format:"Formato", continue:"Continuar", name:"Seu nome", code:"Código do torneio", animal:"Escolha seu animal", strategy:"Estratégia", ready:"Estou pronto", waiting:"Aguardando o organizador", organizer:"Painel do organizador", start:"INICIAR TORNEIO", participants:"Participantes", training:"Treino", arena:"Arena ao vivo", events:"Eventos", bracket:"Chaveamento", save:"Salvar estratégia", total:"Pedra + Papel + Tesoura =", invalid:"A distribuição deve somar 100%.", network:"Não foi possível concluir a ação. Verifique o código ou a conexão.", rateLimited:"Você está fazendo muitas tentativas em pouco tempo. Aguarde alguns segundos e tente novamente.", started:"Torneio iniciado pelo servidor.", rules:"Melhor de", sound:"Efeitos sonoros", music:"Música", audioOn:"Ligados", audioOff:"Desligados", musicOn:"Ligada", musicOff:"Desligada", movement:"Velocidade de movimento", countdown:"Velocidade da contagem" },
  en: { home:"Home", join:"Join tournament", create:"Create tournament", sponsor:"Become a sponsor", sponsored:"Sponsored by", tagline:"🦅 🐼 🦘 🦦 🐵 🐓 🐂 🐯 🐘 🐻 🐙 🦍 🐎 🦙 🦌 🐪 🐐 🦎 🐱 🦓 🦜 🐦 🦁 🐧 🐟 🦈", createTitle:"Build your arena", joinTitle:"Enter the arena", capacity:"Maximum capacity", format:"Format", continue:"Continue", name:"Your name", code:"Tournament code", animal:"Choose your animal", strategy:"Strategy", ready:"I am ready", waiting:"Waiting for organizer", organizer:"Organizer dashboard", start:"START TOURNAMENT", participants:"Participants", training:"Training", arena:"Live arena", events:"Events", bracket:"Bracket", save:"Save strategy", total:"Rock + Paper + Scissors =", invalid:"Each distribution must total 100%.", network:"We could not complete that action. Check the code or connection.", rateLimited:"You are making too many attempts in a short time. Wait a few seconds and try again.", started:"Tournament started by the server.", rules:"Best of", sound:"Sound effects", music:"Music", audioOn:"On", audioOff:"Off", musicOn:"On", musicOff:"Off", movement:"Movement speed", countdown:"Countdown speed" },
  "zh-CN": { home:"首页", join:"加入锦标赛", create:"创建锦标赛", sponsor:"成为赞助商", sponsored:"赞助商", tagline:"🦅 🐼 🦘 🦦 🐵 🐓 🐂 🐯 🐘 🐻 🐙 🦍 🐎 🦙 🦌 🐪 🐐 🦎 🐱 🦓 🐦 🦁 🐧 🐟 🦈", createTitle:"创建你的竞技场", joinTitle:"进入竞技场", capacity:"最大容量", format:"赛制", continue:"继续", name:"你的名字", code:"锦标赛代码", animal:"选择动物", strategy:"策略", ready:"准备好了", waiting:"等待组织者", organizer:"组织者面板", start:"开始锦标赛", participants:"参与者", training:"训练", arena:"实时竞技场", events:"事件", bracket:"对阵表", save:"保存策略", total:"石头 + 布 + 剪刀 =", invalid:"每个分布必须合计为 100%。", network:"无法完成操作。请检查代码或网络。", rateLimited:"短时间内尝试次数过多。请稍候几秒后再试。", started:"锦标赛已由服务器开始。", rules:"三局两胜", sound:"音效", music:"音乐", audioOn:"开启", audioOff:"关闭", musicOn:"开启", musicOff:"关闭", movement:"移动速度", countdown:"倒计时速度" },
  ar: { home:"الرئيسية", join:"انضم إلى البطولة", create:"إنشاء بطولة", sponsor:"كن راعياً", sponsored:"برعاية", tagline:"🦅 🐼 🦘 🦦 🐵 🐓 🐂 🐯 🐘 🐻 🐙 🦍 🐎 🦙 🦌 🐪 🐐 🦎 🐱 🦓 🦜 🐦 🦁 🐧 🐟 🦈", createTitle:"أنشئ ساحتك", joinTitle:"ادخل إلى الساحة", capacity:"السعة القصوى", format:"النظام", continue:"متابعة", name:"اسمك", code:"رمز البطولة", animal:"اختر حيوانك", strategy:"الاستراتيجية", ready:"أنا جاهز", waiting:"بانتظار المنظم", organizer:"لوحة المنظم", start:"ابدأ البطولة", participants:"المشاركون", training:"تدريب", arena:"الساحة المباشرة", events:"الأحداث", bracket:"المواجهات", save:"حفظ الاستراتيجية", total:"حجر + ورق + مقص =", invalid:"يجب أن يساوي مجموع التوزيع 100٪.", network:"تعذر إكمال الإجراء. تحقق من الرمز أو الاتصال.", rateLimited:"تجري محاولات كثيرة خلال وقت قصير. انتظر بضع ثوانٍ ثم حاول مرة أخرى.", started:"بدأت البطولة من قبل الخادم.", rules:"الأفضل من", sound:"المؤثرات الصوتية", music:"الموسيقى", audioOn:"مفعّلة", audioOff:"موقفة", musicOn:"مفعّلة", musicOff:"موقفة", movement:"سرعة الحركة", countdown:"سرعة العد التنازلي" }
} as const;
export type MessageKey = keyof (typeof messages)["pt-BR"];
export function text(locale: Locale, key: MessageKey): string { return messages[locale][key]; }

// Round 7 presentation copy.
Object.assign(interfaceText["pt-BR"], {"narrateAnimal":"Ouvir nome e nome científico","cinemaTie":"EMPATE","cinemaRoundWinner":"Vencedor da rodada","cinemaBracket":"Chaveamento ao vivo","cinemaEvents":"Eventos oficiais","cinema_entrance":"Entrando na Arena","cinema_countdown":"Prepare-se","cinema_reveal":"Jogadas oficiais","cinema_heart":"Coração perdido","cinema_elimination":"Eliminação","cinema_victory":"Vitória da partida","cinema_advance":"Avançando no chaveamento","cinema_bye":"Avanço por BYE","cinema_champion":"CAMPEÃO"});
Object.assign(interfaceText["en"], {"narrateAnimal":"Hear common and scientific name","cinemaTie":"TIE","cinemaRoundWinner":"Round winner","cinemaBracket":"Live bracket","cinemaEvents":"Official events","cinema_entrance":"Entering the Arena","cinema_countdown":"Get ready","cinema_reveal":"Official moves","cinema_heart":"Heart lost","cinema_elimination":"Elimination","cinema_victory":"Match victory","cinema_advance":"Advancing in the bracket","cinema_bye":"Advancing by BYE","cinema_champion":"CHAMPION"});
Object.assign(interfaceText["zh-CN"], {"narrateAnimal":"朗读名称和学名","cinemaTie":"平局","cinemaRoundWinner":"本回合胜者","cinemaBracket":"实时对阵表","cinemaEvents":"官方事件","cinema_entrance":"进入竞技场","cinema_countdown":"准备","cinema_reveal":"官方出招","cinema_heart":"失去一颗心","cinema_elimination":"淘汰","cinema_victory":"对局获胜","cinema_advance":"晋级","cinema_bye":"轮空晋级","cinema_champion":"冠军"});
Object.assign(interfaceText["ar"], {"narrateAnimal":"استمع إلى الاسم والاسم العلمي","cinemaTie":"تعادل","cinemaRoundWinner":"الفائز بالجولة","cinemaBracket":"جدول المواجهات المباشر","cinemaEvents":"الأحداث الرسمية","cinema_entrance":"دخول الساحة","cinema_countdown":"استعد","cinema_reveal":"الحركات الرسمية","cinema_heart":"خسارة قلب","cinema_elimination":"إقصاء","cinema_victory":"الفوز بالمواجهة","cinema_advance":"التقدم في الجدول","cinema_bye":"تأهل تلقائي","cinema_champion":"البطل"});
// Official podium and independent tournament executions.
Object.assign(interfaceText["pt-BR"], { thirdPlaceMatch:"Disputa de 3º Lugar", grandFinal:"Grande Final", firstPlace:"Primeiro Lugar", secondPlace:"Segundo Lugar", thirdPlace:"Terceiro Lugar", podium:"Pódio", repeatTournament:"Repetir Torneio", backToPanel:"Voltar ao painel", newRun:"Nova execução", event_third_place_match_started:"Disputa de terceiro iniciada", event_third_place_decided:"Terceiro lugar definido", event_final_started:"Grande Final iniciada", event_podium_decided:"Pódio definido" });
Object.assign(interfaceText.en, { thirdPlaceMatch:"Third-place match", grandFinal:"Grand Final", firstPlace:"First Place", secondPlace:"Second Place", thirdPlace:"Third Place", podium:"Podium", repeatTournament:"Repeat Tournament", backToPanel:"Back to dashboard", newRun:"New run", event_third_place_match_started:"Third-place match started", event_third_place_decided:"Third place decided", event_final_started:"Grand Final started", event_podium_decided:"Podium decided" });
Object.assign(interfaceText["zh-CN"], { thirdPlaceMatch:"季军赛", grandFinal:"总决赛", firstPlace:"第一名", secondPlace:"第二名", thirdPlace:"第三名", podium:"领奖台", repeatTournament:"再次举办比赛", backToPanel:"返回管理面板", newRun:"新一届比赛", event_third_place_match_started:"季军赛开始", event_third_place_decided:"季军确定", event_final_started:"总决赛开始", event_podium_decided:"领奖台确定" });
Object.assign(interfaceText.ar, { thirdPlaceMatch:"مباراة المركز الثالث", grandFinal:"النهائي الكبير", firstPlace:"المركز الأول", secondPlace:"المركز الثاني", thirdPlace:"المركز الثالث", podium:"منصة التتويج", repeatTournament:"إعادة البطولة", backToPanel:"العودة إلى لوحة المنظم", newRun:"نسخة جديدة", event_third_place_match_started:"بدأت مباراة المركز الثالث", event_third_place_decided:"تحديد المركز الثالث", event_final_started:"بدأ النهائي الكبير", event_podium_decided:"تحديد منصة التتويج" });
Object.assign(interfaceText["pt-BR"], { semifinals:"Semifinais" });
Object.assign(interfaceText.en, { semifinals:"Semifinals" });
Object.assign(interfaceText["zh-CN"], { semifinals:"半决赛" });
Object.assign(interfaceText.ar, { semifinals:"نصف النهائي" });
Object.assign(interfaceText["pt-BR"], { homeJoinAction:"Entrar No Torneio", trainingStrategyAction:"Treinar Estratégia" });
Object.assign(interfaceText.en, { homeJoinAction:"Join Tournament", trainingStrategyAction:"Train Strategy" });
Object.assign(interfaceText["zh-CN"], { homeJoinAction:"加入锦标赛", trainingStrategyAction:"训练策略" });
Object.assign(interfaceText.ar, { homeJoinAction:"انضم إلى البطولة", trainingStrategyAction:"تدرّب على الاستراتيجية" });
