"use client";

import { useState } from "react";
import Link from "next/link";
import { Locale, localeNames, locales } from "../../i18n/catalog";

const copy: Record<Locale, Record<string, string>> = {
  "pt-BR": { hero:"Sua marca 100% dentro da arena", sub:"Associe sua marca a uma experiência que combina estratégia, estatística, tecnologia, competição e entretenimento.", talk:"Quero falar sobre patrocínio", project:"Conhecer o projeto", creator:"Sobre o criador", role:"Estatístico, Gestor Financeiro e Técnico em Eletroeletrônica.", bio:"Vitor Marchetti Craveiro é um eterno estudante e, muitas vezes, professor, curioso por natureza que procura unir estatística, economia, tecnologia, educação e desenvolvimento de projetos para transformar ideias em experiências práticas.", why:"Por que nasceu o RPS: Animal Showdown?", whyText:"O projeto nasceu para tornar dinâmicas de grupo mais divertidas, interativas e memoráveis, mostrando estatística, probabilidade e estratégia de forma prática.", contexts:"Uma experiência que cabe em diferentes ambientes", contextsText:"Escolas, universidades, eventos, hospitais, empresas, treinamentos, confraternizações, palestras, festas, campeonatos e transmissões.", brand:"Sua marca dentro da experiência", brandText:"Um patrocinador principal exclusivo por período, integrado à experiência com presença discreta, logo e link em áreas estratégicas.", benefits:"Benefícios possíveis", benefitList:"Presença principal · Tecnologia e inovação · Estatística e estratégia · Eventos e torneios · Link para site ou rede social · Exclusividade", commercial:"Valores e formatos de patrocínio sob consulta.", commercialText:"Cada parceria pode ser definida conforme período, contexto de uso e formato desejado.", contact:"Vamos conversar?", final:"", finalText:"", home:"Voltar ao projeto", whatsapp:"Falar pelo WhatsApp", email:"Enviar e-mail", linkedin:"Ver LinkedIn" },
  en: { hero:"Your brand 100% inside the arena", sub:"Connect your brand to an experience combining strategy, statistics, technology, competition and entertainment.", talk:"Talk about sponsorship", project:"Discover the project", creator:"About the creator", role:"Statistician, Financial Manager and Electrotechnics Technician.", bio:"Vitor Marchetti Craveiro is a lifelong student and often a teacher, connecting statistics, technology, education and practical projects.", why:"Why was RPS: Animal Showdown created?", whyText:"It makes group activities more interactive and memorable while showing statistics, probability and strategy in practice.", contexts:"An experience for different settings", contextsText:"Schools, universities, events, hospitals, companies, training, gatherings, talks, parties, tournaments and broadcasts.", brand:"Your brand inside the experience", brandText:"One exclusive main sponsor per period, naturally integrated with discreet presence, logo and links.", benefits:"Possible benefits", benefitList:"Main sponsorship · Technology and innovation · Statistics and strategy · Events and tournaments · Website or social link · Exclusivity", commercial:"Sponsorship formats and values on request.", commercialText:"Each partnership can be designed for its period, context and desired format.", contact:"Let's talk?", final:"Your brand can be the next to enter the arena.", finalText:"Get in touch to learn about RPS: Animal Showdown sponsorship options.", home:"Back to project", whatsapp:"WhatsApp", email:"Email", linkedin:"LinkedIn" },
  "zh-CN": { hero:"让您的品牌 100% 进入竞技场", sub:"将您的品牌与战略、统计、技术、竞争和娱乐相结合。", talk:"洽谈赞助", project:"了解项目", creator:"关于创作者", role:"统计学家、财务经理和电工技术员。", bio:"Vitor Marchetti Craveiro 是终身学习者，也常常是教师，将统计、技术、教育和实践项目联系起来。", why:"为什么创建 RPS: Animal Showdown？", whyText:"它让群体活动更有趣、互动且难忘，并以实践方式展示统计、概率和策略。", contexts:"适合不同环境的体验", contextsText:"学校、大学、活动、医院、企业、培训、聚会、演讲、派对、锦标赛和直播。", brand:"让品牌融入体验", brandText:"每个时期一位独家主赞助商，以自然方式呈现品牌、标志和链接。", benefits:"可能的权益", benefitList:"主赞助 · 技术与创新 · 统计与策略 · 活动与锦标赛 · 网站或社交链接 · 独家性", commercial:"赞助形式和价格请咨询。", commercialText:"每项合作可根据周期、使用环境和期望形式制定。", contact:"一起聊聊？", final:"您的品牌可能是下一个进入竞技场的品牌。", finalText:"联系我们，了解 RPS: Animal Showdown 的赞助机会。", home:"返回项目", whatsapp:"WhatsApp", email:"电子邮件", linkedin:"LinkedIn" },
  ar: { hero:"علامتك التجارية 100٪ داخل الساحة", sub:"اربط علامتك بتجربة تجمع الاستراتيجية والإحصاء والتقنية والمنافسة والترفيه.", talk:"التحدث عن الرعاية", project:"اكتشف المشروع", creator:"عن المبتكر", role:"إحصائي ومدير مالي وفني كهرباء وإلكترونيات.", bio:"فيتور ماركيتي كرافييرو طالب دائم ومعلم في كثير من الأحيان، يجمع الإحصاء والتقنية والتعليم والمشاريع العملية.", why:"لماذا وُلد RPS: Animal Showdown؟", whyText:"يجعل الأنشطة الجماعية أكثر تفاعلاً وذكراً، ويعرض الإحصاء والاحتمال والاستراتيجية عملياً.", contexts:"تجربة تناسب بيئات مختلفة", contextsText:"المدارس والجامعات والفعاليات والمستشفيات والشركات والتدريبات والبطولات والبث.", brand:"علامتك داخل التجربة", brandText:"راعٍ رئيسي حصري واحد لكل فترة، بحضور طبيعي وشعار وروابط في مناطق مناسبة.", benefits:"مزايا ممكنة", benefitList:"رعاية رئيسية · تقنية وابتكار · إحصاء واستراتيجية · فعاليات وبطولات · رابط موقع أو شبكة · حصرية", commercial:"صيغ وقيم الرعاية عند الطلب.", commercialText:"تُحدد كل شراكة وفق الفترة والسياق والصيغة المطلوبة.", contact:"لنتحدث؟", final:"قد تكون علامتك التالية لدخول الساحة.", finalText:"تواصل معنا لمعرفة فرص رعاية RPS: Animal Showdown.", home:"العودة للمشروع", whatsapp:"واتساب", email:"البريد الإلكتروني", linkedin:"لينكدإن" },
};

export default function SponsorPage() {
  const [locale, setLocale] = useState<Locale>("pt-BR");
  const c = copy[locale];
  const whatsapp = `https://wa.me/5514998682886?text=${encodeURIComponent("Olá, Vitor! Conheci o RPS: Animal Showdown e gostaria de saber mais sobre as possibilidades de patrocínio.")}`;
  return <main className="sponsor-page" dir={locale === "ar" ? "rtl" : "ltr"}>
    <header className="sponsor-nav"><Link className="back brand" href="/">RPS: <b>ANIMAL</b> SHOWDOWN</Link><div className="locale-switcher">{locales.map((item) => <button key={item} className="locale-choice" aria-pressed={locale === item} onClick={() => setLocale(item)}><span className={`flag flag-${item}`} />{localeNames[item]}</button>)}</div></header>
    <section className="sponsor-hero"><span className="eyebrow">RPS: ANIMAL SHOWDOWN</span><h1>{c.hero}</h1><p>{c.sub}</p><div className="cta-row"><a className="button" href={whatsapp} target="_blank" rel="noreferrer">{c.talk}</a><a className="button secondary" href="#projeto">{c.project}</a></div></section>
    <section id="projeto" className="sponsor-section two"><article><span className="eyebrow">{c.creator}</span><h2>Vitor Marchetti Craveiro</h2><strong>{c.role}</strong><p>{c.bio}</p></article><article className="card"><h2>{c.why}</h2><p>{c.whyText}</p></article></section>
    <section className="sponsor-section"><h2>{c.contexts}</h2><p>{c.contextsText}</p></section>
    <section className="sponsor-section two"><article><h2>{c.brand}</h2><p>{c.brandText}</p></article><article className="card"><h2>{c.benefits}</h2><p>{c.benefitList}</p></article></section>
    <section className="sponsor-section"><h2>{c.commercial}</h2><p>{c.commercialText}</p></section>
    <section className="sponsor-contact"><h2>{c.contact}</h2><div className="cta-row"><a className="button" href={whatsapp} target="_blank" rel="noreferrer">{c.whatsapp}</a><a className="button secondary" href="mailto:v.craveiro@unesp.br?subject=Patrocínio%20—%20RPS%3A%20Animal%20Showdown">{c.email}</a><a className="button secondary" href="https://www.linkedin.com/in/vitor-craveiro-5108b91b2/?isSelfProfile=true" target="_blank" rel="noreferrer">{c.linkedin}</a></div><Link className="back sponsor-back" href="/">← {c.home}</Link></section>
  </main>;
}
